[package]
name = "to_be_free"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["xtask"]


[dependencies]
bevy = "0.18.0"

# Enable ECS debug names (feature-unifies with Bevyâ€™s internal bevy_ecs)
bevy_ecs = { version = "0.18.0", features = ["debug"] }
